spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zzx-data?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000 # ⽤来设置⼀个connection在连接池中的存活时间，默认是1800000，即30分钟。如果设置为0，表⽰存活时间⽆限
logging:
  config: classpath:logback.xml
  level:
    com.fjcpc.zzx: debug # ERROR、WARN、INFO、DEBUG